{% set name = "w3m" %}
{% set version = "0.5.3" %}
{% set sha256 = "e994d263f2fd2c22febfbe45103526e00145a7674a0fda79c822b97c2770a9e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-fix-for-current-gc-lib-and-html-forms.patch
    - 0002-added-setting-of-DYLD_FALLBACK_LIBRARY_PATH.patch  # [osx]
build:
  number: 1002
  skip: True  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ncurses
    - readline
    - gettext
    - libiconv
    - bdw-gc
    - openssl
  run:
    - ncurses
    - readline
    - gettext
    - libiconv
    - bdw-gc
    - openssl

test:
  commands:
    - w3m -help | grep usage

about:
  home: http://w3m.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: "{{ environ['RECIPE_DIR'] }}/LICENSE"
  summary: 'Text mode web browser/pager.'

  # The remaining entries in this section are optional, but recommended
  description: |
    w3m text mode web browser/pager.  Works well with an Emacs front end called emacs-w3m.

extra:
  recipe-maintainers:
    - notestaff
