travis:
  secure:
    BINSTAR_TOKEN: Sk57G3T/YQiL7Jw+EEeuD2mYP/Fq9tf7Q/cJOCoPdJKSIVbM8JFIUII3xOUc7QWySk9QG/R9pUr3nh8D+mONwpUPu1aDziCZN8WgqTLxEDgnLqFR4Xtv/Z3T5MlBg562Z7hwcpR3BmpNvfW4vxvkMp0gmEFu27DRhRPOqeRxKBWHin9VAU3zk1NhlkbrslKnoQf//JnsILMduNhYxW9Rb1Y7Hs8jmlQMGmVtSHD0EwgwkfSVdM++zRbhuqd8r5h9qwVabHBREzpA6zD2llY3FmrIltUjC6qlEzipb84HEom0JjuBKhWc+qFmMACeXyc2BQpe0z9kbhV1BXXPPXfMAQtHR9lLasgKdEM8JLHVKGgjjKgrZCRB0CkCc7exAvC/kxn0k2IoaiR9ZxbRwtlJyTAfAnBwQ5qRXY9NN66wmVkcawiORg6Vx8KsnFJDL/FH/iLQ26nu/qWhPJSUF/EZlwWESjHqowOp7hPjUa3QWjj8d/5fr2psXvbIr9BcPcts9USNMSyoVg1FQ7HI371HQPYHSUwhIWRTn77gxq2LWSJ3w7lHoMFqy0yU2av9g2Fk4+tv8piTiczYjqI/+1Mp2Bs4GjNxpapcHo5KssQ+GXCarQHDV0j5/h19ZkVVpDGX2fnxTs2px2FlNqCB8buA1zOuWzqBPVqBsFd6R23JBkw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
