travis:
  secure:
    BINSTAR_TOKEN: lfTiakwXBB6D3Db4Hqzk1n6rr96s3Arng+TLm1Dh/VrVwmIJBoh8JPRQZgnQGQPohfZWRdWecBIhkAGTZoGNBpmJJo4mWsdbzGHx3lgnaOs20S4RqL8fWRriNJyLzDl7FVCkFm/iQ7yg8/QD4y2DMg/A+1vdYuOe+OoPu3a5xy1rY7+8FbDASee1ibvl+96tCARmg/Qk/RCrMthOSN8FFYUAL5vuH6JyyBEngW5T0U9sRuK5Hz60zcIgECZYxSch2B3JRDbELiepOmp13LyovM5IIkiC2bTkAAZBW+qQu0jRU/UnxLjidAJnFr936O8NQR3bdY/6XGvwKVk8Ni7XwvljvBaw9DrlbSurVotF5lxsKG+Bw25YsTNXeHppPxjx9gDe6zIHjkP1DGiSq+mOMtNtMcv9T8DtJvIHGRh5zlREP4y2kcoF65Jbg9TY/hnTLw2RCS2HH5xEK1GOsV58UHgnrdQ5nKORLjgZ80RjjbiLgZFMiwcmyZJblnYmuNPark2CYgkf/3D9c1pF9lzj7sy+8uiCW9fnVhhgTz9axP4abL1elMnB7+ryPyOYXArW6UqJ1aNh3WpIJO1LoXK09095LBRp5MPZu3qeGhC5acfjwqBU+M36hLmMN3AhxC/EUFB4BjAQUWCB7M2XxDR1qhPEf/REKhOxyOtV7K4vdYM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
