travis:
  secure:
    BINSTAR_TOKEN: ErIpJNFwUPB9LU7pdnTQZBkz+I6YBbZ5X4T+rOjGBOgwSjRDMBXJu9MAywf6IcTRi6I6EQz76VHyYCbvYqqrSXF4rNtqkVyn0v/kY+g4LcAeBlb5X0G5+I/enVLwyplvSLFF/F7OFFNWpDTVVyF76OYtpOSl/HDCaEGj+zELOqxI7Rl2+kH29ChtTYsiLLW0U8WTzv63werC2MFEJHU+b33M5eN1J/akKUpeXUSStBLooT5F9EfqpBK8tHj/wl34LULYHEp9kir7eUsLPtK84Nl1ozj9u9bVt/XcTPDdXkxPt48krBjVONuE61q2f8H66eQIA3w1eNBgsFR/qrJDQ4Nq/DRhxoLlE9MKZPib6uKGrNdk0SROCo3vlGH7Jy2gXsKfxFNkzKnmakW+EixpLRGfW8OQDCLMRvpbq1suP7b/XengITMFmkb7kNZPYVOUTDywhyn31uG5ufbSDPDAce4SBeNWThjYlaISc8hvsrx59TLFwNKIRurNosyQc0Imlkyl2u/sKRR6vHWS5n9vDovF2pOCqRGcM/dCoZnN+0gYQgSap4lwzKZzcJT2VZc0owWTlsp6wPb/sK/k4SUmXSUL5n+zgwdFb6SFpoX2czxqvhNBLuv+3qNBCqrn16uEEFSpNyggg+/VnjHl5jzqr+TeMwRXveGn0Gak6WpuZpQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
